package com.transaction.project.simulator.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AdviceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdviceAllPropertiesEquals(Advice expected, Advice actual) {
        assertAdviceAutoGeneratedPropertiesEquals(expected, actual);
        assertAdviceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdviceAllUpdatablePropertiesEquals(Advice expected, Advice actual) {
        assertAdviceUpdatableFieldsEquals(expected, actual);
        assertAdviceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdviceAutoGeneratedPropertiesEquals(Advice expected, Advice actual) {
        assertThat(expected)
            .as("Verify Advice auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdviceUpdatableFieldsEquals(Advice expected, Advice actual) {
        assertThat(expected)
            .as("Verify Advice relevant properties")
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAdviceUpdatableRelationshipsEquals(Advice expected, Advice actual) {
        assertThat(expected)
            .as("Verify Advice relationships")
            .satisfies(e -> assertThat(e.getMerchant()).as("check merchant").isEqualTo(actual.getMerchant()))
            .satisfies(e -> assertThat(e.getAcquirer()).as("check acquirer").isEqualTo(actual.getAcquirer()));
    }
}
