package com.transaction.project.simulator.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CardTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCardTypeAllPropertiesEquals(CardType expected, CardType actual) {
        assertCardTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertCardTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCardTypeAllUpdatablePropertiesEquals(CardType expected, CardType actual) {
        assertCardTypeUpdatableFieldsEquals(expected, actual);
        assertCardTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCardTypeAutoGeneratedPropertiesEquals(CardType expected, CardType actual) {
        assertThat(expected)
            .as("Verify CardType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCardTypeUpdatableFieldsEquals(CardType expected, CardType actual) {
        assertThat(expected)
            .as("Verify CardType relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCardTypeUpdatableRelationshipsEquals(CardType expected, CardType actual) {
        // empty method
    }
}
