package com.transaction.project.simulator.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FieldTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTypeAllPropertiesEquals(FieldType expected, FieldType actual) {
        assertFieldTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertFieldTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTypeAllUpdatablePropertiesEquals(FieldType expected, FieldType actual) {
        assertFieldTypeUpdatableFieldsEquals(expected, actual);
        assertFieldTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTypeAutoGeneratedPropertiesEquals(FieldType expected, FieldType actual) {
        assertThat(expected)
            .as("Verify FieldType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTypeUpdatableFieldsEquals(FieldType expected, FieldType actual) {
        assertThat(expected)
            .as("Verify FieldType relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFieldTypeUpdatableRelationshipsEquals(FieldType expected, FieldType actual) {
        // empty method
    }
}
