package com.transaction.project.simulator.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MessageTypeIndicatorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageTypeIndicatorAllPropertiesEquals(MessageTypeIndicator expected, MessageTypeIndicator actual) {
        assertMessageTypeIndicatorAutoGeneratedPropertiesEquals(expected, actual);
        assertMessageTypeIndicatorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageTypeIndicatorAllUpdatablePropertiesEquals(MessageTypeIndicator expected, MessageTypeIndicator actual) {
        assertMessageTypeIndicatorUpdatableFieldsEquals(expected, actual);
        assertMessageTypeIndicatorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageTypeIndicatorAutoGeneratedPropertiesEquals(MessageTypeIndicator expected, MessageTypeIndicator actual) {
        assertThat(expected)
            .as("Verify MessageTypeIndicator auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageTypeIndicatorUpdatableFieldsEquals(MessageTypeIndicator expected, MessageTypeIndicator actual) {
        assertThat(expected)
            .as("Verify MessageTypeIndicator relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageTypeIndicatorUpdatableRelationshipsEquals(MessageTypeIndicator expected, MessageTypeIndicator actual) {
        // empty method
    }
}
