package com.transaction.project.simulator.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MessageFieldTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageFieldTypeAllPropertiesEquals(MessageFieldType expected, MessageFieldType actual) {
        assertMessageFieldTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertMessageFieldTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageFieldTypeAllUpdatablePropertiesEquals(MessageFieldType expected, MessageFieldType actual) {
        assertMessageFieldTypeUpdatableFieldsEquals(expected, actual);
        assertMessageFieldTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageFieldTypeAutoGeneratedPropertiesEquals(MessageFieldType expected, MessageFieldType actual) {
        assertThat(expected)
            .as("Verify MessageFieldType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageFieldTypeUpdatableFieldsEquals(MessageFieldType expected, MessageFieldType actual) {
        assertThat(expected)
            .as("Verify MessageFieldType relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageFieldTypeUpdatableRelationshipsEquals(MessageFieldType expected, MessageFieldType actual) {
        assertThat(expected)
            .as("Verify MessageFieldType relationships")
            .satisfies(e -> assertThat(e.getFieldType()).as("check fieldType").isEqualTo(actual.getFieldType()));
    }
}
